# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a457f96f862b21e5ee9534d6145c9e49652b1d0d8c5633e2e3cc9ff6d514ddb23abb12b0eaeedf2c81830eba79ab3874b0c9433773c998739abdc3cb5435c7f

test:
  secret_key_base: 32d3d047c2f4e723ff5ab74c21fc609c4a26a956fe2d1dfe93fcc68dafe979f7ee6e0d929fa506e0826a5f3f8e8f4edb604db1ec0580d4f4f3b15ceafd90b514

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
